export enum Packages {
    fleets = 'fleets',
    snaptoroad = 'snaptoroad',
    adminCustomer = 'adminCutomer',
    snapshots = 'snapshots',
    adminTruck = 'adminTruck',
    liveTraffic = 'liveTraffic',
    predictivemaintenance = 'predictivemaintenance',
    fuelconsumption = 'fuelconsumption',
    quickviewrange = 'quickviewrange',
    adminTerritory = 'adminTerritory',
    fuelfilupexport = 'fuelfilupexport',
    fuelfillupreport = 'fuelfillupreport',
    addfuel = 'addfuel',
    driverreport = 'driverreport',
    adminFuel = 'adminFuel',
    driverbehaviorreport = 'driverbehaviorreport',
    driversAllocation = 'driversAllocation',
    distancetravel = 'distancetravel',
    vehiclereporting = 'vehiclereporting',
    staffForm = 'staffForm',
    vehiclereportsexport = 'vehiclereportsexport',
    battey = 'battey',
    driverdetail = 'driverdetail',
    shiftStatus = 'shiftStatus',
    driverreporting = 'driverreporting',
    addJob = 'addJob',
    jobdistance = 'jobdistance',
    shiftTime = 'shiftTime',
    violationFilters = 'violationFilters',
    maintenanceLog = 'maintenanceLog',
    distanceTravelledToday = 'distanceTravelledToday',
    quickView = 'quickView',
    adddriver = 'adddriver',
    vehiclestate = 'vehiclestate',
    adminUser = 'adminUser',
    profile = 'profile',
    jobanomalyreports = 'jobanomalyreports',
    travelhistory = 'travelhistory',
    fleetdetail = 'fleetdetail',
    ignition = 'ignition'
}

export enum PackageType {
    standard = 6,
    png = 5
}