// Created by soban on 17-12-2017.
export enum JobStatusEnum {
  Active = 1,
  Accepted = 74,
  Completed = 55,
  Collected = 92,
  Aborted = 54,
  InActive = 2,
  Pending = 53,
  Reviewed = 95,
  Running = 52,
  Rejected = 75,
  Resumed = 79,
  Suspended = 78,
  Started = 94,
  UnCollected = 93,
  Conflicting = 96,
  Collect_Waste = 97,
  Waste_Collected = 98,
  Skip_Verification = 116,
  Failed = 117,
}
export enum TruckTypeEnum{
  COMPACTOR = 131,
  HOOK_LOADER = 132,
  CHAIN_LOADER = 133,
  TIPPER_TRUCK = 146,
  SEDAN = 217,
  MOTOR_BIKE = 218,
  
}
export enum MaintenanceStatusEnum {
  MAINTENANCE_OVER_DUE = 71,
  MAINTENANCE_ACCEPTED = 170,
  MAINTENANCE_ADMIN_APPROVAL = 168,
  MAINTENANCE_COMPLETED = 72,
  MAINTENANCE_DUE = 73,
  ADDITION_OF_COST = 167,
  MAINTENANCE_PENDING = 169,
  MAINTENANCE_WAITING_FOR_PARTS = 159,
}


export const JobTypes = {
  ADHOC : 215,
  SCHEDULED : 216,
}


export enum MaintenanceTypeEnum {
  ENGINE_TUNING_MAINTENANCE = 67,
  SERVICE_MAINTENANCE = 68,
  TYRE_REPLACEMENT_MAINTENANCE = 69,
  SUSPENSION_REPAIR_MAINTENANCE = 70,
}
export enum MaintenanceDataEnum {
  MAINTENANCE_DATA_COST_LABOR = 160,
  MAINTENANCE_DATA_COST_PARTS = 161,
  MAINTENANCE_DATA_COST_TAXES = 162,
  MAINTENANCE_DATA_COST_DISCOUNT = 163,
  MAINTENANCE_DATA_COST_FINE = 164,
}

export enum NotificationTypeEnum {
  NOTIFICATION_ADMIN_ACTIVITY_REVIEW = 81,
  NOTIFICATION_ADMIN_ACTIVITY_REVIEW_DRIVER_REJECT = 82,
  NOTIFICATION_ADMIN_ACTIVITY_REVIEW_TRUCK_CONFLICT = 83,
  NOTIFICATION_ADMIN_ACKNOWLEDGE_DRIVER_ABORT = 84,
  NOTIFICATION_ADMIN_ACKNOWLEDGE_DRIVER_ACCEPT = 86,
  NOTIFICATION_ADMIN_ACKNOWLEDGE_DRIVER_SUSPEND = 87,
  NOTIFICATION_ADMIN_ACKNOWLEDGE_DRIVER_RESUME = 88,
  NOTIFICATION_ADMIN_ACKNOWLEDGE_DRIVER_COMPLETE = 89,
  NOTIFICATION_ADMIN_ACKNOWLEDGE_DRIVER_START = 90,
  NOTIFICATION_ADMIN_ACTIVITY_REVIEW_NO_ACTION_ACCEPT_REJECT = 91,
  NOTIFICATION_DRIVER_BIN_PICKUP = 113,
  NOTIFICATION_DRIVER_WASTE_COLLECTION = 114,
  NOTIFICATION_DRIVER_BIN_DROPOFF = 115,
  NOTIFICATION_ADMIN_ACKNOWLEDGE_DRIVER_START_SHIFT = 118,
  NOTIFICATION_ADMIN_ACKNOWLEDGE_DRIVER_END_SHIFT = 119,
  NOTIFICATION_ADMIN_ACTIVITY_REVIEW_NO_ACTION_START_FAIL = 123,
  NOTIFICATION_ADMIN_ADD_ASSET_BIN = 125,
  NOTIFICATION_ADMIN_ADD_ASSET_DRIVER = 126,
  NOTIFICATION_ADMIN_ADD_ASSET_SUPERVISOR = 127,
  NOTIFICATION_ADMIN_ADD_ASSET_RFID_CARD = 128,
  NOTIFICATION_ADMIN_ADD_ASSET_RFID_TAG = 129,
  NOTIFICATION_ADMIN_ADD_ASSET_RFID_SCANNER = 130,
  NOTIFICATION_ADMIN_ACTIVITY_REVIEW_BIN_CONFLICT = 142,




  TASK_COMPLETED = 1504,
  TASK_APPROVED = 1505,

// #Violations
  OUT_OF_ZONE = 1506,
  IN_ZONE = 1509,
  IN_SITE = 1510,
  OUT_OF_SITE = 1511,

// #Attendance
  CHECK_IN = 1507,
  CHECK_OUT = 1508,
}







